### ISSUE TITLE
Full rewrite

### ISSUE THREAD

**Issue by Salamandar** [siredmar/winepatchfusion360installer#5]
I did a full rewrite on my fork (https://github.com/Salamandar/winepatchfusion360installer).

The original script was splitted into functions, and the arg parging is better. It can be sourced to use the functions.

Another script was written, that does the full install (run winetricks and streamer basically).

**Comment by siredmar** [comment]
At a first glance this looks good. I will test it. Do you mind creating a PR?

**Comment by siredmar** [comment]
Merged your ideas. Thanks
