### ISSUE TITLE
Canvas doesn't show unless the graphics driver is set to DirectX9 in Fusion 360

### ISSUE THREAD

**Issue by JeroenDelcour** [siredmar/winepatchfusion360installer#7]
Thanks for this, it all worked beautifully (after installing Vulcan on my host Ubuntu system). Only issue I had was the canvas not showing up (i.e. couldn't see parts). In my case, I had to go into Fusion 360's Preferences -> General -> Graphics driver and set it to DirectX 9 explicitly (instead of the default 'Auto-select'). After a restart, everything showed up and worked correctly.

Not really an issue, but perhaps this saves someone a few hours of trying to figure it out themselves :)

**Comment by siredmar** [comment]
Thanks! I made a notice in the Readme.
