### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by madurani** [siredmar/winepatchfusion360installer#9]
Hello guys,

Guide for installation of Fusion360 worked fine for a long time, but current version of Fusion keeps crashing with some error(details are in png attachment):

error occurs after executing command: `wine streamer.exe -p deploy -g -f log.txt --quiet;"`  

![Fusion360](https://user-images.githubusercontent.com/49711883/79491723-2d441700-801f-11ea-981a-dfe348372092.png)

**Comment by HendrikRoth** [comment]
Same issue here

**Comment by madurani** [comment]
Mistake was found/fixed.  Script downloads file platform.py from path:
`wget "https://raw.githubusercontent.com/python/cpython/master/Lib/platform.py"`

In the path is folder master. It looks, that in master version is python 3.8, but Fusion use python 3.7.
For fixing of problem you only need to change location of path from "master" to "3.7" and installation will finish successfully (only for current version of Fusion360).

Note: Correct path is:
`wget https://raw.githubusercontent.com/python/cpython/3.7/Lib/platform.py`

**Comment by siredmar** [comment]
Fixed the URL. Thanks for reporting!
